language: c++

if:
  (tag IS present \
  AND tag =~ /v([0-9]+\.[0-9]+\.[0-9]+)(-\w*)*/)
  OR branch = master

env:
  matrix:
    - LUA=luajit2.0
script:
  - mkdir build && cd build
  - cmake -D SLW_BUILD_TESTS=ON ..
  - make -j4
  - ./slw-ci
notifications:
  email:
    on_success: change
    on_failure: always
