language: c++

sudo: required
dist: trusty
before_install:
  - sudo apt-get install -y libluajit-5.1
  - sudo apt-get install -y libluajit-5.1-dev 
  - sudo apt-get install -y libluajit-5.1-common
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DSLW_BUILD_TESTS=ON ..
  - make -j4
  - ./tests/slw-ci
notifications:
  email:
    on_success: change
    on_failure: always
