language: c++

if:
  (tag IS present \
  AND tag =~ /v([0-9]+\.[0-9]+\.[0-9]+)(-\w*)*/)
  OR branch = master

dist: trusty
sudo: false

before_install:
	- eval "${MATRIX_EVAL}"
#  - sudo apt-get install -y libluajit-5.1
#  - sudo apt-get install -y libluajit-5.1-common
#  - sudo apt-get install -y libluajit-5.1-dev 

matrix:
	include:
		- os: linux
	addons:
		apt:
			sources:
				- ubuntu-toolchain-r-test
			packages:
				- g++-4.9
				- libluajit-5.1
				- libluajit-5.1-common
				- libluajit-5.1-dev
	env:
		- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

env:
  matrix:
    - LUA=luajit2.0
script:
  - mkdir build && cd build
  - cmake -D SLW_BUILD_TESTS=ON ..
  - make -j4
  - ./slw-ci
notifications:
  email:
    on_success: change
    on_failure: always
