language: c++
if:
  (tag IS present \
  AND tag =~ /v([0-9]+\.[0-9]+\.[0-9]+)(-\w*)*/) \
  OR branch = master
dist: trusty
sudo: false
matrix:
	include:
		- os: linux
	    addons:
    		apt:
		    	sources:
				    - ubuntu-toolchain-r-test
    			packages:
		    		- g++-6
				    - libluajit-5.1
    				- libluajit-5.1-common
		    		- libluajit-5.1-dev
    	env:
		    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
	- eval "${MATRIX_EVAL}"
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DSLW_BUILD_TESTS=ON ..
  - make -j4
  - ./slw-ci
notifications:
  email:
    on_success: change
    on_failure: always
